#-------------------------------------------------------------------------------
# Description:
#   The purpose of this service definition, is to define a way to get the
#   contents of a file existing in an ABB robot controller system.
#
# Note:
#   The file is assumed to be located in the system's home directory.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Service request fields
#-------------------------------------------------------------------------------
# Filename (including file extension) of the targeted file.
string filename

---

#-------------------------------------------------------------------------------
# Service response fields
#-------------------------------------------------------------------------------
# Contents of the file.
string contents

# Service success/failure indicator.
# Refer to 'abb_robot_msgs/ServiceResponses' for defined error codes.
uint16 result_code

# Status message (empty if service succeeded).
string message
