#-------------------------------------------------------------------------------
# Description:
#   The purpose of this service definition, is to define a way to get a
#   (partial) description of an ABB robot controller system.
#
# Note:
#   The description will be returned in a Google Protocol Buffer text format.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Service request fields
#-------------------------------------------------------------------------------

---

#-------------------------------------------------------------------------------
# Service response fields
#-------------------------------------------------------------------------------
# Description of the robot controller system.
string description

# Service success/failure indicator.
# Refer to 'abb_robot_msgs/ServiceResponses' for defined error codes.
uint16 result_code

# Status message (empty if service succeeded).
string message
