<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypeset="xml"?>
<package format="3">
  <name>ur5_moveit_config</name>
  <version>1.0.0</version>
  <description>MoveIt configuration for UR5 with Robotiq gripper</description>
  <maintainer email="your.email@cranfield.ac.uk">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <exec_depend>moveit_ros_move_group</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>ros2srrc_ur5_gazebo</exec_depend>
  <exec_depend>ros2srrc_execution</exec_depend>
  <exec_depend>machine_vision_exercise</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>