#-------------------------------------------------------------------------------
# Description:
#   The purpose of this message definition, is to represent the custom RAPID
#   data type "EGMStopSettings" from the RobotWare "StateMachine Add-In".
#
# Note:
#   "EGMStopSettings" are for example used with the RAPID EGM instruction
#   "EGMStop".
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Message fields
#-------------------------------------------------------------------------------
# Ramp out time [s].
float32 ramp_out_time
